### ISSUE TITLE
How can I generate retriever_candidate

### ISSUE THREAD

**Issue by qiaoqiao228** [WEIYanbin1999/KICGPT#1]
I plan to use my own built dataset on the program, realizing that the program requires "retriever_candidate_tail. txt" and "retriever_candidate_head. txt". I noticed that the dataset you provided includes the above files. How can I generate a retriever on my own dataset. Thank you for your help.

**Comment by WEIYanbin1999** [comment]
To get retriever results, you should first choose a classic/advanced link prediction retriever. For example, in our experiment, the retriever is set as RotatE. 
Then you should use this retriever(RotatE) to run the link prediction,  and record its top m prediction results in "retriever_candidate_tail. txt" and "retriever_candidate_head. txt".
