### ISSUE TITLE
monetary cost

### ISSUE THREAD

**Issue by gyf6666** [WEIYanbin1999/KICGPT#2]
Hi author, is it convenient to disclose roughly how many dollars it cost you to run a dataset（for example fb15k_237 or wn18rr） based on API_KEY?

**Comment by WEIYanbin1999** [comment]
Our work used third-party forwarded and Lab-shared keys, the records are nested with other work usage, resulting in tracing historical quota toughly.
However, I can provide an estimate strategy to you:
 1. Randomly choosing n samples from the dataset
 2. Perform the KICGPT link prediction, via the real key you plan to use, and calculate the average cost.  
     OR You can also use the same tokenizer to pre-calculate the token and calculate the cost by your API-KEY pricing policy, for that, our codes did provide a case for estimating query token numbers.
 3. Scale up to the whole set
 
Wish it is helpful to you.
